openapi: 3.1.0
info:
  version: 0.0.0
  title: Power Play API
  description: Developer documentation for the PowerPlay app
  license:
    name: MIT
    url: https://opensource.org/license/mit

paths:
  /auth:
    $ref: "./auth/auth.yml#/paths/auth"
  /users:
    $ref: "./users/users.yml#/paths/users"
  /users/{id}:
    $ref: "./users/users.yml#/paths/users~1{id}"
  /dev/db:
    $ref: "./dev/dev.yml#/paths/dev~1db"


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
